language: csharp
mono: none
os: linux

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

install:
  - wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
  - chmod +x ./dotnet-install.sh
  - ./dotnet-install.sh -c 8.0 --install-dir $HOME/dotnet
  - export PATH=$PATH:$HOME/dotnet
  - export DOTNET_ROOT=$HOME/dotnet

script:
  - dotnet --version
  - dotnet restore
  - dotnet build LittleRestClient.sln --configuration Release /p:WarningLevel=0
  - dotnet test LittleRestClient/UnitTestProject.csproj --configuration Release /p:WarningLevel=0
  - dotnet pack LittleRestClient/LittleRestClient.csproj --configuration Release -o ./nupkgs
